appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Jy+QSSt15EXdqXJbm2loJqYMwTEdEgjMglNso24jM4JDw9Dclyqu3C6J/LgKcN8TzxC6LW2hnQTt9lQsjHe7IWLFsWVEU9m7yQw/Z6qh+peZBHy0aOr6NRMdrZqDnqxmBsTwYaKB2ekKf+5cGS+x1XKLJQR0hwMUugQtN9UZ7BplMKk8uAlZLciLr7fruhghmvxSjDsMpK8p+2gHzvjYgDSUMe0gRIb3I5THNQ4FmodBo18kmGQC9Ki30epk9ZWAWl/3Njfb+PpRiJC/RFoma/GS4GKfmEQnEQwDjeLBvMSZOQjSHHZFzK516K9Y5MjSc2dYp95GUduhiaVL4BhJCF6PMocPDxg07gsgCqF2IF+NdQ3rGaDjv8BP4MVkt66iKKJMSoz5J91Eu3A8Ut7vdHZar3VPYusp/b44v0uNEED537l9syv/zNOBEHpwh8Z/b2QAR8Noe+p3LhnAaWiBTHqE3yEmIp5mrFZKQao2qJmQ9BDsDvvBKeWZBIsFGPMDjljKp0miuGWGJgLjksK4yveh+f+Y4gAu1cTJNHd5960Sv2OGYfizEjir6goSdaWPp+5w6x60DvL/SKAwjrZZKbHHPvVHTKMIT9wE4jk/GsCjA6zuP1m3EUd+PSHxJof3/8Nh/bd+mWDyr4jCfPBAISpL1kIe639BIBKL9SvJIrg=}
conda_forge_output_validation: true
