travis:
  secure:
    BINSTAR_TOKEN: BR9uPe1ii7kzMAEcHQQH7eAa+/FLsQHZRVHfrK6a1u6IDcPjV1cm5rkWybP5f6zjqCQgGaME2nF+5jCdtBLSAr2F8BfH+I1v0O7rn3/246mg89LVyS0tURxdip4dcL569IXM/uqHzdc+5Fukk8u4dzF+G9X5CjGEwVQwI30nIOjIDPm5nwI65Fo2bWonUIrXcEnL85dQcjW5j7bJ8g/taBRcWu++nmD5KkNw2d0jUgyAOLJjAaxIQX4FiPcYy40NwFE+BosFfAopNIhIjfLEIs3y12ED7HftTg4ZcZ7P7vmjSc0Rab29vgB6bTrn4BcYzr9rT3zojDWHWE/S96/QjUWW81eYdgeMUquRcT4MTmk75Iiw/RDnfQJ14/qR0ymLcgiWi6EbqfYRwz5qIc+EAsA2JD6U5UAsnEzcvROi+ec/gDPafwuX5bJXX5fCYFu2y2rD84DZV7FHlv232vKg166nYbdS9FXsbhYF/0NJike/vFGEm4u2Lz8EcSmFsG9zcbHDCldsXuSA+MaTslaESUFg8bMxw+tA2cHfzG16NlcRNn8g3x+HDnwyi2hkZq+h9TqsceGVRFshT7F8CuMv4KOOmKFi40MwQVMgdNZAbeoVEleQ+7wZG2+zJFa7g+1Atq3ZWYqH/6JhKApEzid9xxO0bLayITsYXtCS9lch1Pc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
