travis:
  secure:
    BINSTAR_TOKEN: EXCmrRdi9Db5SROhBxJQn2huUUUyTgG3H4CcBcD5SEye7Mt1OMF7E6+DYBpJiwfClaL8AtSRknVnjqYjO+SkDib9w2JDeQ24QTdSYzb+KM3kcD4JzsvOy+oJXGQm92amxgMEQnF+TaqYVCdpQMvbQLZBYpmhb328dyjn0eQsY3P+3QpnNhUU1m6K675UiJIBhfteW6xV4qxGJc/bdcc2ogz+iRqsRfYJygvUk1G8NhCjxlKYX0sW5+2DWKZXJvFD/0j4+vLE37aouVs0rouCgUPTqolIr++HU1eiGFoOUVN0RxxlrEIhCNRxkNHGFZluL/3lfWlidgB9xV+jsoMNRc3L/cWz3w/6dlH2aKT7UYCSwLrM/uQ9xGdzAKC99ry+77DbXg1qB5+d5xyvA+TC5Te61GIlOgqNgnQDSL1kUDmHHf1BJm9jVAqu6lZ8WfMyiGd9cfrtpPNtvMVFGr+bX+PMYJWoNP+KAg6H3A7Y9qYr5cgrP58jUy3e4ENBSZvMcwnv6J1vimosFtGxQqO8BWt44lrq/VtdU8Cg9oEGT+d1QP54PPLYJRRUvUq3hz7JvPP+gygoLz0ZA8PBnwhQYvtjP7fDxkhw3do4GPX+6Ehr+/ZJD9NjtpUly0VpgAnBMZP7T001aj1KLCV2BP0JEosi0KxGuH+1DpxSw1e2WeA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
